apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limitrange-training
spec:
  limits:
  - default:
      memory: 500Mi
    defaultRequest:
      memory: 500Mi
    max:
      memory: 1Gi
    min:
      memory: 100Mi
    type: Container
