apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: docker.io/nginx:latest
      ports:
        - containerPort: 8080
  nodeName: worker
