apiVersion: v1
kind: Pod
metadata:
  name: myapp-nodeaffinity
spec:
  containers:
    - name: myapp-nodeaffinity
      image: docker.io/nginx:latest
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: size
           operator: In
           values:
           - Large
           - Medium
       - matchExpressions:
         - key: size
           operator: NotIn
           values:
           - small

