apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-defined-resources
  labels:
    app: myapp-with-defined-resources
spec:
  containers:
    - name: myapp-with-defined-resources
      image: docker.io/nginx:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2
