apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: nginx
    tier: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx-containers
        image: docker.io/nginx:latest
  replicas: 3
  selector:
    matchLabels:
      tier: frontend


# kubectl scale replicaset.apps/myapp-replicaset --replicas=5
