apiVersion: v1
kind: Pod
metadata:
  name: env-var-pod
  labels:
    name: env-var-pod
spec:
  containers:
    - name: nginx
      image: docker.io/nginx:latest
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config
