apiVersion: v1
kind: Pod
metadata:
  name: env-var-pod
  labels:
spec:
  containers:
    - name: nginx
      image: docker.io/nginx:latest
      ports:
        - containerPort: 8080
      env:
        - name: APP_color
          value: pink
      env:
        - name: APP_color
          valueFrom:
            configMapKeyRef:
      env:
        - name: APP_color
          valueFrom:
            secretKeyRef:
